@echo off

:: Note: you might need to change paths in this batch file in order to build yourself

echo Build Bat File
echo Precheck the Resource 
"D:\Data\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" save "D:\Data\dev\mre\nope\nope.vcproj"
echo Compiling gccmain.c
"D:\Data\dev\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -static -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\Data\dev\mre\nope\arm\gccmain.o" -c "D:\Data\MRE SDK V3.0.00\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "D:\Data\MRE SDK V3.0.00\include" -I "D:\Data\MRE SDK V3.0.00\include\service" -I "D:\Data\MRE SDK V3.0.00\include" -I "D:\Data\MRE SDK V3.0.00\include\service" -I "D:\Data\dev\mre\nope\include" -I "D:\Data\dev\mre\nope\include\service" -I "D:\Data\dev\mre\nope\include\component" -I "D:\Data\dev\mre\nope\ResID" -I "D:\Data\dev\mre\nope\src\app\widget" -I "D:\Data\dev\mre\nope\src\app\launcher" -I "D:\Data\dev\mre\nope\src\app\wallpaper" -I "D:\Data\dev\mre\nope\src\app\screen_lock" -I "D:\Data\dev\mre\nope\include\service" -I "D:\Data\dev\mre\nope\include\component" -I "D:\Data\dev\mre\nope\include\service" -I "D:\Data\dev\mre\nope\src\framework" -I "D:\Data\dev\mre\nope\src\framework\ui_core\base" -I "D:\Data\dev\mre\nope\src\framework\ui_core\mvc" -I "D:\Data\dev\mre\nope\src\framework\ui_core\pme" -I "D:\Data\dev\mre\nope\src\framework\mmi_core" -I "D:\Data\dev\mre\nope\src\ui_engine\vrt\interface" -I "D:\Data\dev\mre\nope\src\component" -I "D:\Data\dev\mre\nope\src\ui_engine\framework\xml" -I "D:\Data\dev\mre\nope"
echo Compiling none.c
"D:\Data\dev\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -static -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\Data\dev\mre\nope\arm\nope.o" -c "d:\Data\dev\mre\nope\nope.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "D:\Data\MRE SDK V3.0.00\include" -I "D:\Data\MRE SDK V3.0.00\include\service" -I "D:\Data\MRE SDK V3.0.00\include" -I "D:\Data\MRE SDK V3.0.00\include\service" -I "D:\Data\dev\mre\nope\include" -I "D:\Data\dev\mre\nope\include\service" -I "D:\Data\dev\mre\nope\include\component" -I "D:\Data\dev\mre\nope\ResID" -I "D:\Data\dev\mre\nope\src\app\widget" -I "D:\Data\dev\mre\nope\src\app\launcher" -I "D:\Data\dev\mre\nope\src\app\wallpaper" -I "D:\Data\dev\mre\nope\src\app\screen_lock" -I "D:\Data\dev\mre\nope\include\service" -I "D:\Data\dev\mre\nope\include\component" -I "D:\Data\dev\mre\nope\include\service" -I "D:\Data\dev\mre\nope\src\framework" -I "D:\Data\dev\mre\nope\src\framework\ui_core\base" -I "D:\Data\dev\mre\nope\src\framework\ui_core\mvc" -I "D:\Data\dev\mre\nope\src\framework\ui_core\pme" -I "D:\Data\dev\mre\nope\src\framework\mmi_core" -I "D:\Data\dev\mre\nope\src\ui_engine\vrt\interface" -I "D:\Data\dev\mre\nope\src\component" -I "D:\Data\dev\mre\nope\src\ui_engine\framework\xml" -I "D:\Data\dev\mre\nope"
echo Linking app 
"D:\Data\dev\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\Data\dev\mre\nope\nope.axf"  "D:\Data\dev\mre\nope\arm\gccmain.o"  "D:\Data\dev\mre\nope\arm\nope.o" -O3 -static -fpic -msvr4-struct-return -pie  -T "D:\Data\MRE SDK V3.0.00\lib\MRE30\armgcc\scat.ld" -l:"D:\Data\MRE SDK V3.0.00\lib\MRE30\armgcc\percommon.a" -l:"D:\Data\MRE SDK V3.0.00\lib\MRE30\armgcc\persensor.a" -l:"D:\Data\MRE SDK V3.0.00\lib\MRE30\armgcc\perbitstream.a" -l:"D:\Data\MRE SDK V3.0.00\lib\MRE30\armgcc\perfile.a"
echo Pack resource to app 
"D:\Data\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\Data\dev\mre\nope\nope.pkd" -e AXF "D:\Data\dev\mre\nope\nope.vcproj" "D:\Data\dev\mre\nope\nope.axf"
echo Add tag infromation 
"D:\Data\MRE SDK V3.0.00\tools\PackDigist.exe" "D:\Data\dev\mre\nope\nope.vcproj" "nope" "0.1.0" "giangvinhloc610" "2000" "NotSupportBg" "Not Support rotate" "nope" "nope" "nope" "1234567890" "content" " Sensor BitStream File" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "" "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\Data\dev\mre\nope\arm D:\Data\dev\mre\nope\build.log

